# Generated by Django 3.1.7 on 2021-03-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('dateOfCreation', models.DateField(verbose_name='Дата создания')),
                ('deadlineDate', models.DateField(verbose_name='Дедлайн')),
                ('ownerName', models.CharField(blank='True', max_length=255, null=True, verbose_name='Создатель')),
                ('mark', models.BooleanField(default=False, verbose_name='Готовность')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
