# Generated by Django 3.1.7 on 2021-03-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0002_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название списка')),
                ('dateOfCreation', models.DateField(verbose_name='Дата Создания')),
            ],
            options={
                'verbose_name': 'Список Заданий',
                'verbose_name_plural': 'Списки Заданий',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('dateOfCreation', models.DateField(verbose_name='Дата создания')),
                ('deadlineDate', models.DateField(verbose_name='Дедлайн')),
                ('ownerName', models.CharField(blank='True', max_length=255, null=True, verbose_name='Создатель')),
                ('mark', models.BooleanField(default=False, verbose_name='Готовность')),
                ('todoList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.todolist', verbose_name='Задания списка')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
